// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package main

import "encoding/json"

// cli commands and parameters
type CliCommands struct {
	// AddSchema corresponds to the JSON schema field "add-schema".
	AddSchema *CliCommandsAddSchema `json:"add-schema,omitempty"`

	// AddTransformer corresponds to the JSON schema field "add-transformer".
	AddTransformer *CliCommandsAddTransformer `json:"add-transformer,omitempty"`

	// ApplyTransform corresponds to the JSON schema field "apply-transform".
	ApplyTransform *CliCommandsApplyTransform `json:"apply-transform,omitempty"`

	// Connect corresponds to the JSON schema field "connect".
	Connect *CliCommandsConnect `json:"connect,omitempty"`

	// ListPayloads corresponds to the JSON schema field "list-payloads".
	ListPayloads *CliCommandsListPayloads `json:"list-payloads,omitempty"`

	// ListSchemas corresponds to the JSON schema field "list-schemas".
	ListSchemas *bool `json:"list-schemas,omitempty"`

	// ListTransformers corresponds to the JSON schema field "list-transformers".
	ListTransformers *bool `json:"list-transformers,omitempty"`

	// ServeJsonl corresponds to the JSON schema field "serve-jsonl".
	ServeJsonl *CliCommandsServeJsonl `json:"serve-jsonl,omitempty"`

	// Summary corresponds to the JSON schema field "summary".
	Summary *bool `json:"summary,omitempty"`
}

type CliCommandsAddSchema struct {
	// Content corresponds to the JSON schema field "content".
	Content *string `json:"content,omitempty"`
}

type CliCommandsAddTransformer struct {
	// Content corresponds to the JSON schema field "content".
	Content *string `json:"content,omitempty"`
}

type CliCommandsApplyTransform struct {
	// Spec corresponds to the JSON schema field "spec".
	Spec *string `json:"spec,omitempty"`
}

type CliCommandsConnect struct {
	// MQTT host for connection
	MqttHost string `json:"mqtt-host,omitempty"`

	// MQTT port for connection
	MqttPort int `json:"mqtt-port,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CliCommandsConnect) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	type Plain CliCommandsConnect
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	if v, ok := raw["mqtt-host"]; !ok || v == nil {
		plain.MqttHost = "localhost"
	}
	if v, ok := raw["mqtt-port"]; !ok || v == nil {
		plain.MqttPort = 1883.0
	}
	*j = CliCommandsConnect(plain)
	return nil
}

type CliCommandsListPayloads struct {
	// Type corresponds to the JSON schema field "type".
	Type *string `json:"type,omitempty"`
}

type CliCommandsServeJsonl struct {
	// port to serve JSONL on
	Port int `json:"port,omitempty"`

	// path to JSONL file to serve
	Source *string `json:"source,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CliCommandsServeJsonl) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	type Plain CliCommandsServeJsonl
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	if v, ok := raw["port"]; !ok || v == nil {
		plain.Port = 8080.0
	}
	*j = CliCommandsServeJsonl(plain)
	return nil
}
