// Package main provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version 2.1.0 DO NOT EDIT.
package main

import (
	"fmt"
	"net/http"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// Error defines model for Error.
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// Record defines model for Record.
type Record = map[string]interface{}

// Records defines model for Records.
type Records = []Record

// ListRecordsParams defines parameters for ListRecords.
type ListRecordsParams struct {
	// Limit Number of records to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of records to skip
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Count all records
	// (GET /count)
	CountRecords(ctx echo.Context) error
	// List paginated records
	// (GET /records)
	ListRecords(ctx echo.Context, params ListRecordsParams) error
	// Info for a specific record
	// (GET /records/{index})
	ShowRecordById(ctx echo.Context, index int) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// CountRecords converts echo context to params.
func (w *ServerInterfaceWrapper) CountRecords(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CountRecords(ctx)
	return err
}

// ListRecords converts echo context to params.
func (w *ServerInterfaceWrapper) ListRecords(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRecordsParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", ctx.QueryParams(), &params.Offset)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListRecords(ctx, params)
	return err
}

// ShowRecordById converts echo context to params.
func (w *ServerInterfaceWrapper) ShowRecordById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "index" -------------
	var index int

	err = runtime.BindStyledParameterWithOptions("simple", "index", ctx.Param("index"), &index, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter index: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ShowRecordById(ctx, index)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/count", wrapper.CountRecords)
	router.GET(baseURL+"/records", wrapper.ListRecords)
	router.GET(baseURL+"/records/:index", wrapper.ShowRecordById)

}
